services:

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      interval: 5s
#      timeout: 5s
#      retries: 5
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - ./env/mysql.env
    environment:
      TZ: "Asia/Seoul"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

#  app:
#    build: ./
#    ports:
#      - "8080:8080"
#    env_file:
#      - ./env/mysql.env
#      - ./env/server.env
#    depends_on:
#      mysql:
#        condition: service_healthy
