services:

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - ./env/mysql.env

  app:
    build: ./
    ports:
      - "8080:8080"
    env_file:
      - ./env/mysql.env
    depends_on:
      mysql:
        condition: service_healthy
