server:
  port: 8081

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  data:
    redis:
      host: localhost
      port: 6379

# local에서만
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
      hibernate: DEBUG

aes256:
  secret:
    key: ${AES256_SECRET_KEY}
    iv: ${AES256_SECRET_IV}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}